export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";

export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";

export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

export const LOAD_PROJECTS_SUCCESS = "LOAD_PROJECTS_SUCCESS";

export const LOAD_PROJECTS_FAILURE = "LOAD_PROJECTS_FAILURE";

export const LOAD_PROJECT_SUCCESS = "LOAD_PROJECT_SUCCESS";

export const LOAD_PROJECT_FAILURE = "LOAD_PROJECT_FAILURE";
